---
title: "EDS 223 Discussion 1"
author: "Max P"
format: html
editor: visual
---

## Load packages

```{r}
library(here)
library(tidyverse)
library(stars)
library(sf)
library(tmap)
```

## Load data

```{r}
ei_points <- sf::read_sf(here::here("data", "easter_island", "ei_points.gpkg"))
volcanoes <- subset(ei_points, type == "volcano")
ei_elev <- stars::read_stars(here::here("data", "easter_island", "ei_elev.tif"))
ei_borders <- sf::read_sf(here::here("data", "easter_island", "ei_border.gpkg"))
ei_roads <- sf::read_sf(here::here("data", "easter_island", "ei_roads.gpkg"))
```

## Start making the static map

```{r}
tmap_mode("plot")

tm_shape(ei_elev) + 
  tm_graticules(lines = FALSE) +
  tm_raster(palette = terrain.colors(6),
            title = "Elevation (m)") + 
tm_shape(ei_borders) + 
  tm_borders(lwd = 3.5) + 
tm_shape(ei_roads) + 
  tm_lines(col = "black", 
           lwd = 1.5, 
           legend.col.show = TRUE) +
tm_shape(volcanoes) + 
  tm_dots(col = "red", size = 0.5, 
          title.size = "Volcanoes") + 
tm_compass() + 
  tm_scale_bar() +
  tm_layout(legend.position = c("left", "top"))
```

## Make the interactive map

```{r}
tmap_mode("view")

tm_shape(ei_elev) + 
  tm_graticules(lines = FALSE) +
  tm_raster(palette = terrain.colors(6),
            title = "Elevation (m)") + 
tm_shape(ei_borders) + 
  tm_borders(lwd = 3) + 
tm_shape(ei_roads) + 
  tm_lines(col = "black", lwd = 1.5) +
tm_shape(volcanoes) + 
  tm_dots(col = "red", size = 0.5, 
          title = "Volcanoes")
```











